baseURL = "https://espa-atocadayhundida.pages.dev/"
title = "España Tocada y Hundida"
languageCode = "es-es"
theme = "PaperMod"
paginate = 10
enableRobotsTXT = true

[params]
  defaultTheme = "dark"
  disableThemeToggle = true
  hideFooter = true
  ShowBreadCrumbs = false
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = false
  mainSections = ["posts"]  # Solo muestra posts en home
  hideMainMenu = true       # Oculta menú principal

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]

[build]
  publishDir = "public"
