baseURL = "https://espa-atocadayhundida.pages.dev/"
title = "España Tocada y Hundida | Clips y Crítica Política"
languageCode = "es-es"
theme = "PaperMod"
paginate = 10
enableRobotsTXT = true

[params]
  defaultTheme = "dark"
  disableThemeToggle = false  # Botón de tema oscuro/claro ACTIVADO
  hideFooter = false          # Footer RESTAURADO
  ShowBreadCrumbs = false
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  mainSections = ["posts"]
  hideMainMenu = true          # Menú OCULTO (como pediste)

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]

[build]
  publishDir = "public"
