baseURL = "https://espa-atocadayhundida.pages.dev/"
title = "España Tocada y Hundida | Clips y Crítica Política"
languageCode = "es-es"
theme = "PaperMod"
paginate = 10
enableRobotsTXT = true

[params]
  defaultTheme = "dark"
  disableThemeToggle = false
  hideFooter = false
  ShowBreadCrumbs = false
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  mainSections = ["posts"]

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]

[build]
  publishDir = "public"
