baseURL = "https://espa-atocadayhundida.pages.dev/"
title = "España Tocada y Hundida"
languageCode = "es-es"
theme = "PaperMod"
paginate = 10

[params]
  defaultTheme = "dark"
  disableThemeToggle = true
  hideFooter = true
  ShowBreadCrumbs = false
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = false
  mainSections = ["posts"]
  hideMainMenu = true

[outputs]
  home = ["HTML"]
  page = ["HTML"]

[build]
  writeStats = false
